version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfile.api
    container_name: api
    ports:
      - "8009:3000"
    environment:
      - DATABASE_URL=postgresql://car_markt_owner:npg_5P0XbLWYhkdE@ep-calm-sound-a9cpcee2-pooler.gwc.azure.neon.tech/car_markt?sslmode=require
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
