version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfile.api
    container_name: api
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
