export const productsList = [
  {
    name: 'Car Engine Oil',
    description:
      'High-performance synthetic engine oil for smooth engine operation.',
    price: 39.99,
    image: 'products/car-engine-oil.jpg',
    stripePriceId: 'price_xxxxx_engineoil',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Car Air Freshener',
    description: 'Long-lasting fragrance to keep your car smelling fresh.',
    price: 4.99,
    image: 'products/car-air-freshener.jpg',
    stripePriceId: 'price_xxxxx_freshener',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Windshield Wiper Blades',
    description: 'Durable and streak-free wiper blades for clear visibility.',
    price: 15.99,
    image: 'products/wiper-blades.jpg',
    stripePriceId: 'price_xxxxx_wipers',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Leather Seat Covers',
    description: 'Premium leather covers for a stylish and comfortable ride.',
    price: 89.99,
    image: 'products/seat-covers.jpg',
    stripePriceId: 'price_xxxxx_seatcovers',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Car Cleaning Kit',
    description: 'Complete kit for exterior and interior car cleaning.',
    price: 29.99,
    image: 'products/car-cleaning-kit.jpg',
    stripePriceId: 'price_xxxxx_cleankit',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Portable Jump Starter',
    description: 'Compact and powerful jump starter for emergency use.',
    price: 59.99,
    image: 'products/jump-starter.jpg',
    stripePriceId: 'price_xxxxx_jumpstarter',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Car Vacuum Cleaner',
    description: 'Handheld vacuum cleaner for car interiors.',
    price: 24.99,
    image: 'products/car-vacuum.jpg',
    stripePriceId: 'price_xxxxx_vacuum',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Alloy Wheel Cleaner',
    description: 'Special formula for cleaning alloy wheels.',
    price: 9.99,
    image: 'products/wheel-cleaner.jpg',
    stripePriceId: 'price_xxxxx_wheelclean',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Dashboard Polish',
    description: 'Protects and shines your car dashboard.',
    price: 7.99,
    image: 'products/dashboard-polish.jpg',
    stripePriceId: 'price_xxxxx_polish',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'LED Headlights',
    description: 'Bright and energy-efficient LED headlights.',
    price: 49.99,
    image: 'products/led-headlights.jpg',
    stripePriceId: 'price_xxxxx_ledlights',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Tire Pressure Gauge',
    description: 'Accurate gauge to monitor tire pressure.',
    price: 11.99,
    image: 'products/tire-pressure-gauge.jpg',
    stripePriceId: 'price_xxxxx_pressure',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'GPS Navigation System',
    description: 'Reliable GPS system with real-time traffic updates.',
    price: 129.99,
    image: 'products/gps-navigation.jpg',
    stripePriceId: 'price_xxxxx_gps',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
  {
    name: 'Roof Cargo Box',
    description: 'Spacious and aerodynamic roof box for extra storage.',
    price: 199.99,
    image: 'products/roof-cargo-box.jpg',
    stripePriceId: 'price_xxxxx_cargobox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Bluetooth FM Transmitter',
    description: 'Stream music and take calls hands-free.',
    price: 19.99,
    image: 'products/fm-transmitter.jpg',
    stripePriceId: 'price_xxxxx_transmitter',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Rearview Camera',
    description: 'Assists in reversing with clear rear visibility.',
    price: 39.99,
    image: 'products/rearview-camera.jpg',
    stripePriceId: 'price_xxxxx_camera',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Car Battery Charger',
    description: 'Smart charger for all car battery types.',
    price: 49.99,
    image: 'products/battery-charger.jpg',
    stripePriceId: 'price_xxxxx_charger',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Sunshade Windshield Cover',
    description: 'Blocks UV rays and keeps car interior cool.',
    price: 14.99,
    image: 'products/sunshade-cover.jpg',
    stripePriceId: 'price_xxxxx_sunshade',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'OBD2 Scanner Tool',
    description: 'Diagnose car issues with this easy-to-use scanner.',
    price: 34.99,
    image: 'products/obd2-scanner.jpg',
    stripePriceId: 'price_xxxxx_obd2',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Car Phone Mount',
    description: 'Secure mount for your phone while driving.',
    price: 9.99,
    image: 'products/phone-mount.jpg',
    stripePriceId: 'price_xxxxx_mount',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Emergency Roadside Kit',
    description: 'Complete kit for roadside emergencies.',
    price: 44.99,
    image: 'products/roadside-kit.jpg',
    stripePriceId: 'price_xxxxx_roadkit',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
];
