# docker/Dockerfile.frontend

FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx nx build car-markt-web
RUN mv dist/apps/car-markt-web/browser/index.csr.html dist/apps/car-markt-web/browser/index.html


FROM nginx:alpine

COPY --from=builder /app/dist/apps/car-markt-web/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf